---
- name: BIG-IP SETUP
  hosts: F5-01
  connection: local
  gather_facts: false

  tasks:
    - name: Setup provider
      ansible.builtin.set_fact:
        provider:
          server: "{{ ansible_host }}"
          # user: "{{ f5_admin_user }}"
          # password: "{{ f5_admin_password }}"
          server_port: "443"
          validate_certs: false
          
    - name: CREATE POOL
      f5networks.f5_modules.bigip_pool:
        provider: "{{ provider }}"
        name: "App_pool"
        lb_method: "round-robin"
        monitors: "/Common/https"
        monitor_type: "and_list"
        
    - name: ADD POOL MEMBERS
      f5networks.f5_modules.bigip_pool_member:
        provider: "{{ provider }}"
        state: "present"
        name: "Member-1"
        host: "172.16.20.20"
        port: "443"
        pool: "App_pool"
    
    - name: ADD VIRTUAL SERVER
      f5networks.f5_modules.bigip_virtual_server:
        provider: "{{ provider }}"
        name: "test_VIP"
        destination: "172.16.10.50"
        port: "443"
        enabled_vlans: "all"
        all_profiles: ['http', 'clientssl', 'oneconnect']
        snat: "Automap"
        pool: "App_pool"

    - name: SAVE RUNNING CONFIG ON BIG-IP
      f5networks.f5_modules.bigip_config:
        provider: "{{ provider }}"
        save: true
